### ISSUE TITLE
default arguments for Markov economy fail on getEconomyData step

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#557]
Running this code, simplified from `KrusellSmith` DemARK:

```
from HARK.ConsumptionSaving.ConsAggShockModel import AggShockMarkovConsumerType, CobbDouglasMarkovEconomy

agent = AggShockMarkovConsumerType()
economy = CobbDouglasMarkovEconomy(
    agents = [agent])

agent.getEconomyData(economy) # Makes attributes of the economy, attributes of the agent
``

Gets this error:

```
$ python consagg.py 
Traceback (most recent call last):
  File "consagg.py", line 7, in <module>
    agent.getEconomyData(economy) # Makes attributes of the economy, attributes of the agent
  File "/home/sb/projects/econ-ark/HARK/HARK/ConsumptionSaving/ConsAggShockModel.py", line 170, in getEconomyData
    self.addAggShkDstn(Economy.AggShkDstn)       # Combine idiosyncratic and aggregate shocks into one dstn
  File "/home/sb/projects/econ-ark/HARK/HARK/ConsumptionSaving/ConsAggShockModel.py", line 400, in addAggShkDstn
    self.IncomeDstn = self.IncomeDstnWithoutAggShocks
AttributeError: 'AggShockMarkovConsumerType' object has no attribute 'IncomeDstnWithoutAggShocks'
```

If this is the correct way to call this function, the default parameters for the two classes should support it without error

**Comment by mnwhite** [comment]
This is the correct way to call the function.  The default parameters for
AggShockMarkovConsumerType do not fully specify how to construct the
idiosyncratic income distribution.  In fact, I never quite came up with a
way to really do so; I kind of intended the user to do it "by hand".

To get it to work properly, all you have to do is add the
line agent.IncomeDstn[0] = 2*[agent.IncomeDstn[0]] right after agent is
initialized.  Essentially, when an AggShockMarkovConsumerType is
initialized, it isn't actually told how many macroeconomic Markov states
there are.  It just creates its own income distribution as if there's no
such thing as a Markov state.  Thus IncomeDstn doesn't actually have the
correct structure when getEconomyData() is run.

That line simply replicates the idiosyncratic income distribution twice in
IncomeDstn[0].  I should rewrite updateIncomeProcess() for this class so
that it constructs IncomeDstn correctly, and that different income
structures can be specified for different states.  Looking at the code, it
seems that the baseline MarkovConsumerType (no aggregate shocks) also has
this flaw.

**Comment by sbenthall** [comment]
Ok, since you seem to understand a fix for this, I'll assign this ticket to you @mnwhite

**Comment by sbenthall** [comment]
Punting until 1.1 because @mnwhite  is currently unavailable

**Comment by mnwhite** [comment]
I believe this is still an outstanding issue, but is significantly easier to tackle with the constructors framework.

To be clear: I'm fairly sure that the AggShockMarkov model doesn't initialize properly with default parameters.
