### ISSUE TITLE
AttributeError: 'KrusellSmithType' object has no attribute 'MrkvInit'

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/HARK#849]
The following code:

```
from HARK.ConsumptionSaving.ConsAggShockModel import KrusellSmithType

agent = KrusellSmithType()
agent.reset()
```

Produces the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sb/projects/econ-ark/HARK/HARK/ConsumptionSaving/ConsAggShockModel.py", line 944, in reset
    self.initializeSim()
  File "/home/sb/projects/econ-ark/HARK/HARK/ConsumptionSaving/ConsAggShockModel.py", line 950, in initializeSim
    self.MrkvNow = self.MrkvInit
AttributeError: 'KrusellSmithType' object has no attribute 'MrkvInit'
```

**Comment by mnwhite** [comment]
KrusellSmithType can't exist separately from a KrusellSmithEconomy. This
attribute is filled in by getEconomyData.

**Comment by sbenthall** [comment]
Ah, makes sense.
Maybe it could have a more informative error message then.

**Comment by mnwhite** [comment]
This is for me to fix.
